# Generated by Django 5.0.1 on 2024-04-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_images_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
