# Generated by Django 5.0.1 on 2024-04-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0010_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='verb',
        ),
    ]
