# Generated by Django 5.0.1 on 2024-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
